### ISSUE TITLE
[TensorRT] ERROR: UFFParser: Parser error: input_2: Invalid number of Dimensions 0

### ISSUE THREAD

**Issue by jinfagang** [parallel-forall/code-samples#9]
I run the code-samples/TensorRT3.1/convert.ipynb, but got this error:
```
[TensorRT] INFO: UFFParser: parsing input_2
[TensorRT] ERROR: UFFParser: Parser error: input_2: Invalid number of Dimensions 0
[TensorRT] ERROR: Failed to parse UFF model stream
  File "/usr/local/lib/python3.5/dist-packages/tensorrt/utils/_utils.py", line 186, in uff_to_trt_engine
    assert(parser_result)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorrt/utils/_utils.py", line 186, in uff_to_trt_engine
    assert(parser_result)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "convert.py", line 124, in <module>
    create_and_save_inference_engine()
  File "convert.py", line 99, in create_and_save_inference_engine
    trt.infer.DataType.FLOAT
  File "/usr/local/lib/python3.5/dist-packages/tensorrt/utils/_utils.py", line 194, in uff_to_trt_engine
    raise AssertionError('UFF parsing failed on line {} in statement {}'.format(line, text))
AssertionError: UFF parsing failed on line 186 in statement assert(parser_result)

```
We registered the input_1 as input why it still try to parse input_2?
Many appreciate if got any reply!

**Comment by faustomilletari** [comment]
Could you please post here a snippet of your code in order to see where the problem is? This is only necessary if you are not running the example as we provide it in the repo.

**Comment by jinfagang** [comment]
I am using convert-tf-to-uff tool found that it is input_2 not input_1

**Comment by gsandeep1231** [comment]
Inside this file there are 2 APIs `/usr/local/lib/python3.5/dist-packages/tensorrt/utils/_utils.py`
I have always found issue with `uff_to_trt_engine`, however `uff_file_to_trt_engine` works just fine. The only different is in the later you pass the actual uff file and not the uff model.

**Comment by Akhtar303nu** [comment]
Hi @jinfagang have you solved this issue?
if you solved ,please share the code
Error
File "/usr/local/lib/python3.5/dist-packages/tensorrt/utils/_utils.py", line 194, in uff_to_trt_engine
    raise AssertionError('UFF parsing failed on line {} in statement {}'.format(line, text))
AssertionError: UFF parsing failed on line 186 in statement assert(parser_result)
Thanks
